### ISSUE TITLE
exit in line 11 of setup.sh? $OFFSET with two values?

### ISSUE THREAD

**Issue by Modiug** [hardillb/rpi-gadget-image-creator#10]
You introduced an exit in line 11 of setup.sh. So, the script actually does nothing.

Another thing:
Trying to mount manually I see that for "2023-10-10-raspios-bookworm-armhf-lite.img" OFFSET looks like this:
```
$ OFFSET=$(fdisk -l 2023-10-10-raspios-bookworm-armhf-lite.img | awk '/^[^ ]*1/{ print $2*512 }')
$ echo $OFFSET
4194304 541065216
```

That $OFFSET with two values won't work with the mount command:
```
$ sudo mount -o loop,offset=$OFFSET 2023-10-10-raspios-bookworm-armhf-lite.img boot
mount: bad usage
Try 'mount --help' for more information.
```

**Comment by hardillb** [comment]
Should be fixed now.

The exit was a testing thing that slipped out, the other was something that only showed up with the new bookworm image.
