### ISSUE TITLE
Latest Raspbian Kernel broken (5.x)

### ISSUE THREAD

**Issue by hardillb** [hardillb/rpi-gadget-image-creator#4]
With the latest kernels the Pi boots fine and all the libcomposite parts come up.

A ethernet device is created on the host (tested with Ubuntu 18.04) for just long enough to get a DHCP address then it stalls and is restarted.

Works with raspbian 2020-02-13 build but not with newer

**Comment by hardillb** [comment]
I need to find somewhere to raise this with upsteam

**Comment by hardillb** [comment]
Upstream issue https://github.com/raspberrypi/linux/issues/3862

**Comment by benjaminwood** [comment]
Thanks for sharing your work on this. I see a good bit of discussion in the upstream issue that you opened. Do I understand there may be a tweak that can be made to work around the problem?

> I can get it to work if I use the usb-gadget.sh-alternative (which fires up a rndis ethernet device via libcomposite) but not ECM (usb-gadget.sh-orig)

**Comment by hardillb** [comment]
No, the alternative is a setup that works with a Windows host machine (using a RNDIS adapter rather than a ECM) it does also work with Linux but not OSx.

I've closed the upstream issue as it looks to have been an issue with my old laptop.
