### ISSUE TITLE
Ubuntu Image?

### ISSUE THREAD

**Issue by jodfie** [hardillb/rpi-gadget-image-creator#5]
Is it possible to tweak this to work with Ubuntu 20.04 or 20.10 Server instead?

**Comment by hardillb** [comment]
Probably

**Comment by jodfie** [comment]
Any ideas on what I would need to change to get it to flip over?

**Comment by hardillb** [comment]
Not really, I don't use Ubuntu on Raspberry Pi Hardware. Some people looked at it in the [comments](https://www.hardill.me.uk/wordpress/2019/11/02/pi4-usb-c-gadget/#comment-13240) of the original blog post, but hit issues iirc

**Comment by notDavid** [comment]
If anyone finds more detailed info/a guide on how to get this working on Ubuntu, please comment here :)

**Comment by notDavid** [comment]
FYI, someone posted a solution here (i haven't tested it yet):

https://www.raspberrypi.org/forums/viewtopic.php?p=1752908&sid=19f6cf5a7e27a539156a938c7f49c6ea#p1752908
