### ISSUE TITLE
Support For Raspberry Pi Model A?

### ISSUE THREAD

**Issue by Patronics** [hardillb/rpi-gadget-image-creator#7]
Does this script support the Raspberry Pi model A or A+? 

I know the procedure is mostly the same for setting it up as for the Zero, except that you need to specifically set it to peripheral device mode, with the following line in config.txt: `dtoverlay=dwc2,dr_mode=peripheral`.

**Comment by hardillb** [comment]
It has never been tried on a A or A+ as I don't have one. If it needs something different to a Zero then it probably won't.
