### ISSUE TITLE
RPi 4 lastest Raspbian Image doesn't come with default pi user.

### ISSUE THREAD

**Issue by cluesang** [hardillb/rpi-gadget-image-creator#8]
Based off of Debin 11. The lastest raspbian OS doesn't come with a default user "pi" you have to follow the steps listed [here](https://www.raspberrypi.com/documentation/computers/configuration.html#configuring-a-user).

In short in the /boot folder you have to add a userconf.txt file with the contents of "username:password" The pass word ought to be generated with openssl encryption. 

I may modify test and submit a PR, but I don't have a lot of time at the moment. So I'll make a not of it here in the meantime. 

Love this idea btw. Thanks!

**Comment by hardillb** [comment]
Yep, I knew this would break things...

Likewise I don't have much spare time at the moment, so a PR would be welcome

**Comment by LanaTPG** [comment]
was going to make a PR, but wanted to ask - as this script currently has no user input (which is nice), what is the best thing to do? 

should we now ask for the desired username and password on script startup (sometimes not convenient as I work with a few PIs at a time), should we just default it to pi:raspberry and ask users to change it later, or, (this is what I think is best) should we add a config file containing raspberry:pi by default, which can be modified should the user decide to do so?

**Comment by hardillb** [comment]
Start simple, hard code the old default values at the top of the script with a big comment about what to change and add a section to the readme

**Comment by hardillb** [comment]
Fixed in https://github.com/hardillb/rpi-gadget-image-creator/commit/6ddaf065543f108d8855615f0ae39c140af3d6a8
